export const SYNTAX_PAGES: Record<string, string[]> = {
  shell: [
    "Data Desk · POSIX-flavored shell. Same engines as the pages. Type use MSFT to focus.",
    "",
    "GRAMMAR",
    "  cmd [args] [key=value]     verbs take flags or k=v",
    "  stmt ; stmt                sequence",
    "  cmd | filter               pipe stdout into a filter",
    "  a && b                     run b if a succeeded",
    "  a || b                     run b if a failed",
    "  for x in a b c; do …; done",
    "  if [ $WACC -gt 9 ]; then …; else …; fi",
    "  case $TAPE in rich) … ;; *) … ;; esac",
    "  name() { … }               function, call as: name",
    "  $(cmd)                     command substitution",
    "  # comment",
    "",
    "VARIABLES  (expanded before the command runs)",
    "  $TAPE $WACC $TGR $YEAR     live numbers, percents as 9.0 not 0.09",
    "  ${TAPE}                    same",
    "  export wacc=9              writes the model knob (and $WACC)",
    "",
    "TEST  [ expr ]   also: test expr",
    "  $WACC -gt 9     -ge -lt -le -eq -ne",
    "  $NAME = foo     string equal / !=",
    "  -n $X   -z $X   non-empty / empty",
    "",
    "QUOTING",
    "  awk '{print $1}'           REQUIRED. Otherwise $1 is eaten by the shell.",
    "  grep -i services",
    "  echo \"tape is $TAPE\"",
    "",
    "EXAMPLES",
    "  quote | grep DCF",
    "  table hist | awk 'NR>1 {s+=$2} END {print s}'",
    "  dcf && reverse",
    "  if [ $TAPE -gt 250 ]; then reverse; else dcf; fi",
    "  for c in quote dcf capm; do $c | head 2; done",
    "  watch quote 12",
    "",
    "Type  help awk   or  syntax awk   for the filter language.",
    "Type  help table  for machine-readable datasets.",
    "F1 catalog · ⌘K palette · Tab completes",
  ],
  awk: [
    "awk — pattern-directed scanning. Real fields, real arithmetic.",
    "usage: <cmd> | awk [-Fsep] [-v var=val] '{program}'",
    "",
    "Always quote the program so the desk does not expand $1.",
    "",
    "STRUCTURE",
    "  BEGIN { … }     once, before any line  (no $0 yet)",
    "  pattern { … }   per line, if pattern is true",
    "  { … }           every line",
    "  END { … }       after the last line",
    "  A pattern with no block is `{print}`.",
    "",
    "FIELDS",
    "  $0              whole line",
    "  $1, $2, $NF     fields (default FS = whitespace)",
    "  NF NR FNR       field count, record number",
    "  FS OFS          input / output field separator",
    "  -F,             set FS to comma   also: BEGIN{FS=\",\"}",
    "",
    "PATTERNS",
    "  NR>1            skip the header",
    "  $2>400          numeric compare",
    "  /2025/          regex against $0",
    "  $1 ~ /iPhone/",
    "",
    "STATEMENTS",
    "  print $1, $2          OFS between args, ORS after",
    "  printf \"%.2f\\n\", $3",
    "  s+=$2                 assignment, += -= *= /=",
    "  if (x>0) print x; else print 0",
    "  for (i=1;i<=NF;i++) print $i",
    "  for (k in a) print k, a[k]",
    "  while (i<10) i++",
    "  next   exit",
    "",
    "BUILTINS",
    "  length substr index split sprintf",
    "  int sqrt log exp sin cos atan2 rand srand",
    "  gsub sub match toupper tolower",
    "",
    "EXAMPLES ON THIS DESK",
    "  table hist | awk 'NR>1 {print $1, $2}'",
    "  table hist | awk '$1+0>2000 {s+=$2} END {print \"rev $B\", s}'",
    "  table hist | awk 'NR>1 {if(p) printf \"%s  %+.1f%%\\n\", $1, 100*($2-p)/p; p=$2}'",
    "  table mix  | awk 'NR>1 {printf \"%s  services %.1f%%\\n\", $1, $6*100}'",
    "  table tape | awk 'NR>1 {if($3>m) m=$3} END {print m}'",
    "  table fcf  | awk 'NR>1 {s+=$4} END {print \"FCF $B\", s}'",
    "  hist | awk '/202[1-5]/ {print}'",
    "",
    "Not a toy: the same interpreter sums, filters, and joins live tables.",
  ],
  table: [
    "table — machine-readable datasets for awk / grep / cut.",
    "usage: table [hist|mix|pnl|cash|tape|peers|fcf|intraday]",
    "",
    "First line is the header. Numbers are raw (no $ or % signs),",
    "so awk arithmetic is honest.",
    "",
    "  hist       year revenue netIncome gm services eps price opIncome",
    "  mix        year iphone mac ipad wearables services     (fractions)",
    "  pnl        year rev gp ebitda ebit ebt ni              ($B)",
    "  cash       year cash buybacks capex fcf                ($B)",
    "  tape       i label close ret                           (live daily)",
    "  peers      sym price chg pe mcap                       (live)",
    "  fcf        year revenue ebit fcf pv                    (live DCF $B)",
    "  intraday   i label close ret                           (session bars)",
    "",
    "  table hist | awk 'NR>1 {s+=$3} END {print s}'",
    "  table tape | awk 'NR>1 {r+=$4} END {print r}'",
    "  table      (lists names)",
  ],
  pipes: [
    "FILTERS  — they only run on the right of a pipe.",
    "",
    "  grep [-v] [-i] [-E] pattern",
    "  awk  [-Fsep] [-v k=v] '{program}'",
    "  head [-n] N          first N lines (default 10)",
    "  tail [-n] N          last N lines",
    "  wc [-l]              line count",
    "  sort [-r]            numeric-aware",
    "  uniq                 adjacent duplicates",
    "  cut -fN              Nth whitespace field",
    "  tr a b               replace",
    "  sed s/a/b/[g]        substitute",
    "  tee                  pass through",
    "",
    "  hist | grep 2025",
    "  table mix | cut -f1",
    "  dcf | head 4 | sed s/DCF/fair/",
  ],
  keys: [],
};

SYNTAX_PAGES.keys = [
  "↑ / ↓            history",
  "Tab              complete the token",
  "⌘K / Ctrl+K      command palette",
  "Ctrl+R           reverse-i-search",
  "Ctrl+L           clear scrollback",
  "Ctrl+C           stop watcher",
  "F1               help",
  "Alt+1…9          switch tabs",
  "Esc              close editor / palette",
];

export function syntaxPage(topic?: string): string[] {
  const t = (topic ?? "shell").toLowerCase();
  if (t === "man") return syntaxPage("shell");
  if (t === "posix" || t === "sh" || t === "zsh" || t === "bash") return SYNTAX_PAGES.shell!;
  if (t === "filter" || t === "filters" || t === "pipe" || t === "grep") return SYNTAX_PAGES.pipes!;
  if (t === "awk" || t === "gawk") return SYNTAX_PAGES.awk!;
  if (t === "table" || t === "tables" || t === "tsv") return SYNTAX_PAGES.table!;
  if (t === "keys" || t === "keyboard" || t === "shortcuts") return SYNTAX_PAGES.keys!;
  if (t === "shell" || t === "syntax" || t === "help") return SYNTAX_PAGES.shell!;
  return [
    `No syntax page for '${topic}'. Try: syntax shell | awk | table | pipes | keys`,
    ...SYNTAX_PAGES.shell!.slice(0, 8),
  ];
}
