/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as DcfRouteImport } from './routes/dcf'
import { Route as DeckRouteImport } from './routes/deck'
import { Route as ForecastRouteImport } from './routes/forecast'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as LiveRouteImport } from './routes/live'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PathsRouteImport } from './routes/paths'
import { Route as PrintRouteImport } from './routes/print'
import { Route as RiskRouteImport } from './routes/risk'
import { Route as SensitivityRouteImport } from './routes/sensitivity'
import { Route as SimulateRouteImport } from './routes/simulate'
import { Route as TermRouteImport } from './routes/term'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const DcfRoute = DcfRouteImport.update({
  id: '/dcf',
  path: '/dcf',
  getParentRoute: () => rootRouteImport,
} as any)
const DeckRoute = DeckRouteImport.update({
  id: '/deck',
  path: '/deck',
  getParentRoute: () => rootRouteImport,
} as any)
const ForecastRoute = ForecastRouteImport.update({
  id: '/forecast',
  path: '/forecast',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveRoute = LiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PathsRoute = PathsRouteImport.update({
  id: '/paths',
  path: '/paths',
  getParentRoute: () => rootRouteImport,
} as any)
const PrintRoute = PrintRouteImport.update({
  id: '/print',
  path: '/print',
  getParentRoute: () => rootRouteImport,
} as any)
const RiskRoute = RiskRouteImport.update({
  id: '/risk',
  path: '/risk',
  getParentRoute: () => rootRouteImport,
} as any)
const SensitivityRoute = SensitivityRouteImport.update({
  id: '/sensitivity',
  path: '/sensitivity',
  getParentRoute: () => rootRouteImport,
} as any)
const SimulateRoute = SimulateRouteImport.update({
  id: '/simulate',
  path: '/simulate',
  getParentRoute: () => rootRouteImport,
} as any)
const TermRoute = TermRouteImport.update({
  id: '/term',
  path: '/term',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dcf': typeof DcfRoute
  '/deck': typeof DeckRoute
  '/forecast': typeof ForecastRoute
  '/history': typeof HistoryRoute
  '/live': typeof LiveRoute
  '/login': typeof LoginRoute
  '/paths': typeof PathsRoute
  '/print': typeof PrintRoute
  '/risk': typeof RiskRoute
  '/sensitivity': typeof SensitivityRoute
  '/simulate': typeof SimulateRoute
  '/term': typeof TermRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dcf': typeof DcfRoute
  '/deck': typeof DeckRoute
  '/forecast': typeof ForecastRoute
  '/history': typeof HistoryRoute
  '/live': typeof LiveRoute
  '/login': typeof LoginRoute
  '/paths': typeof PathsRoute
  '/print': typeof PrintRoute
  '/risk': typeof RiskRoute
  '/sensitivity': typeof SensitivityRoute
  '/simulate': typeof SimulateRoute
  '/term': typeof TermRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dcf': typeof DcfRoute
  '/deck': typeof DeckRoute
  '/forecast': typeof ForecastRoute
  '/history': typeof HistoryRoute
  '/live': typeof LiveRoute
  '/login': typeof LoginRoute
  '/paths': typeof PathsRoute
  '/print': typeof PrintRoute
  '/risk': typeof RiskRoute
  '/sensitivity': typeof SensitivityRoute
  '/simulate': typeof SimulateRoute
  '/term': typeof TermRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/dcf'
    | '/deck'
    | '/forecast'
    | '/history'
    | '/live'
    | '/login'
    | '/paths'
    | '/print'
    | '/risk'
    | '/sensitivity'
    | '/simulate'
    | '/term'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/dcf'
    | '/deck'
    | '/forecast'
    | '/history'
    | '/live'
    | '/login'
    | '/paths'
    | '/print'
    | '/risk'
    | '/sensitivity'
    | '/simulate'
    | '/term'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/dcf'
    | '/deck'
    | '/forecast'
    | '/history'
    | '/live'
    | '/login'
    | '/paths'
    | '/print'
    | '/risk'
    | '/sensitivity'
    | '/simulate'
    | '/term'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  DcfRoute: typeof DcfRoute
  DeckRoute: typeof DeckRoute
  ForecastRoute: typeof ForecastRoute
  HistoryRoute: typeof HistoryRoute
  LiveRoute: typeof LiveRoute
  LoginRoute: typeof LoginRoute
  PathsRoute: typeof PathsRoute
  PrintRoute: typeof PrintRoute
  RiskRoute: typeof RiskRoute
  SensitivityRoute: typeof SensitivityRoute
  SimulateRoute: typeof SimulateRoute
  TermRoute: typeof TermRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dcf': {
      id: '/dcf'
      path: '/dcf'
      fullPath: '/dcf'
      preLoaderRoute: typeof DcfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deck': {
      id: '/deck'
      path: '/deck'
      fullPath: '/deck'
      preLoaderRoute: typeof DeckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forecast': {
      id: '/forecast'
      path: '/forecast'
      fullPath: '/forecast'
      preLoaderRoute: typeof ForecastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live': {
      id: '/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof LiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paths': {
      id: '/paths'
      path: '/paths'
      fullPath: '/paths'
      preLoaderRoute: typeof PathsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/print': {
      id: '/print'
      path: '/print'
      fullPath: '/print'
      preLoaderRoute: typeof PrintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/risk': {
      id: '/risk'
      path: '/risk'
      fullPath: '/risk'
      preLoaderRoute: typeof RiskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sensitivity': {
      id: '/sensitivity'
      path: '/sensitivity'
      fullPath: '/sensitivity'
      preLoaderRoute: typeof SensitivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulate': {
      id: '/simulate'
      path: '/simulate'
      fullPath: '/simulate'
      preLoaderRoute: typeof SimulateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/term': {
      id: '/term'
      path: '/term'
      fullPath: '/term'
      preLoaderRoute: typeof TermRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  DcfRoute: DcfRoute,
  DeckRoute: DeckRoute,
  ForecastRoute: ForecastRoute,
  HistoryRoute: HistoryRoute,
  LiveRoute: LiveRoute,
  LoginRoute: LoginRoute,
  PathsRoute: PathsRoute,
  PrintRoute: PrintRoute,
  RiskRoute: RiskRoute,
  SensitivityRoute: SensitivityRoute,
  SimulateRoute: SimulateRoute,
  TermRoute: TermRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
